### ISSUE TITLE
Initramfs 

### ISSUE THREAD

**Issue by ps4gentoo** [DFAUS-git/ps4-baikal-5.4.0-kernel#1]
Why do you make like this in Initramfs in the init
...
use rootdelay rootdelay
sleep 2
mount LABEL=psxitarch /newroot
sleep 3
emount /newroot
...

this is totaly wrong . you have to add more sleep time before he try to mount the External Drive because of Slow Drives ....like this
...
use rootdelay rootdelay
sleep 8
mount LABEL=psxitarch /newroot

emount /newroot
...

**Comment by DFAUS-git** [comment]
> Why do you make like this in Initramfs in the init ... use rootdelay rootdelay sleep 2 mount LABEL=psxitarch /newroot sleep 3 emount /newroot ...
> 
> this is totaly wrong . you have to add more sleep time before he try to mount the External Drive because of Slow Drives ....like this ... use rootdelay rootdelay sleep 8 mount LABEL=psxitarch /newroot
> 
> emount /newroot ...

Noted, thanks

Other than the firmware files I haven't made any updates to the initramfs, I would say they are heavily outdated, maybe it's time I start looking at it more...

Just to confirm with the above message, you are removing the second sleep call but extending the first call to 8 seconds for slower drive scans?

**Comment by ps4gentoo** [comment]
yes

**Comment by DFAUS-git** [comment]
> yes

Updated, thanks

Closed.
